services:
  - type: web
    name: ethiopian-orthodox-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    autoDeploy: true